### ISSUE TITLE
The display doesn't work ... 

### ISSUE THREAD

**Issue by michaelsomerville** [theshka/visitorTracking#2]
Call to a member function displayThisVisit() on a non-object in

**Comment by michaelsomerville** [comment]
Okay, sorry got it to work.

I am getting this error though now 

``` php
Warning: Call to private visitorTracking::__destruct() from context '' during shutdown ignored in Unknown on line 0
```

**Comment by theshka** [comment]
What PHP version are you using? Thanks

**Comment by theshka** [comment]
693b125 should close this issue.
